[project]
name = "adventofcode2023"
version = "0.1.0"
description = "Add a short description here"
authors = ["Chris Martin <cmartin@palantir.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]

[dependencies]
python = "3.12.0.*"
setuptools = "68.2.2.*"
